taskapp/taskapp/task/urls.py
from django.urls import path

from . import views

app_name = 'task'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('get-tasks/', views.get_task, name='get-tasks'),
    path('get-chart-data/', views.get_chart_data, name='get-chart-data'),
]

taskapp/taskapp/taskapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/', include('task.urls'), name="task-dashboard"),
    path('', RedirectView.as_view(url='/task/', permanent=False)),
]

taskapp/taskapp/task/models.py
from django.db import models
from django.utils.timezone import now

class Task(models.Model):
    COMPLETE = "Complete"
    INCOMPLETE = "Incomplete"
    STATUS = [
        (COMPLETE, "Complete"),
        (INCOMPLETE, "Incomplete")
    ]

    detail = models.CharField(max_length=200, null=False, blank=False)
    status = models.CharField(max_length=200, choices=STATUS,default=INCOMPLETE)
    category = models.CharField(max_length=200, default=None)
    creation_date = models.DateTimeField('Creation Date', default=now)

    def __str__(self):
        return self.detail

taskapp/taskapp/task/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core import serializers
import json
import string
from .models import Task
from django.db.models import Count, Q
from django.contrib import messages
 

def index(request):
    task_list = Task.objects.order_by('-creation_date')
    context = {'task_list': task_list}
    return render(request, 'task/index.html', context)

def add(request):
    if request.method == "POST":
        if(request.POST['detail'] != "" and request.POST['category'] != ""):
            task = Task(detail=request.POST['detail'], status=Task.INCOMPLETE, category=string.capwords(request.POST['category']))
            task.save()
            return HttpResponseRedirect(reverse('task:index'));

        messages.error(request, "Task Detail & Category can't be blank" )
    else:
        messages.error(request, "Wrong Method" )
    return HttpResponseRedirect(reverse('task:index'));


def delete(request):
    if request.method == "POST":
        post_body = json.loads(request.body)
        task = get_object_or_404(Task, pk=post_body.get("id"))
        task.delete()    
        return HttpResponse(json.dumps({
            "success": "deleted"
        }), content_type="application/json")  

    return HttpResponse(json.dumps({
            "error": "Method Not Supported"
        }), content_type="application/json")      

    
def update(request):
    if request.method == "POST":
        post_body = json.loads(request.body)
        task = get_object_or_404(Task, pk=post_body.get("id"))
        task.status = Task.COMPLETE if post_body.get("status") == "True" else Task.INCOMPLETE
        task.save(update_fields=['status'])
        return HttpResponse(json.dumps({
            "success": "updated"
        }), content_type="application/json")    

    return HttpResponse(json.dumps({
            "error": "Method Not Supported"
        }), content_type="application/json")    

def get_chart_data(request):
    task =  Task.objects.values('category').annotate(complete=Count("status", filter=Q(status=Task.COMPLETE)), incomplete=Count("status", filter=Q(status=Task.INCOMPLETE)))
    return HttpResponse(json.dumps(list(task)), content_type="application/json")

def get_task(request):
    task_list = Task.objects.order_by('-creation_date')
    task_list_json = serializers.serialize('json', task_list)

    return HttpResponse(task_list_json, content_type="application/json")

taskapp/taskapp/task/templates/task/index.html
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Task Manager App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    </head>
    <body>
        
        <div class="content">
            <section>
                <header>
                    <h2 class="text-center">Task App</h2>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </header>
                <form class="input-section" action="{% url 'task:add' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" placeholder="Task Category" name="category" class=""/>
                    <input type="text" placeholder="Task Detail" name="detail" class=""/>
                    <button type="submit">+</button>
                </form>
                <div class="list-section">
                    {% if task_list %}
                        <ul>
                        {% for task in task_list %}
                            <li class="card {% if task.status == 'Complete' %}completed{% endif %}" id="task-{{ task.id }}">
                                <div class="task-info">
                                    <span><input type="checkbox" name="task-{{ task.id }}" class="status" {% if task.status == 'Complete' %}checked{% endif %}/> {{ task.detail }}  </span>
                                    <span class="task-category">{{ task.category }}</span>
                                </div>
                                <span class="delete-button">X</span>
                            </li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p class="text-center">No Task to be Done</p>
                    {% endif %}
                </div>
    
            </section>
            
            <section class="chart-section">
                <div id="chartContainer" style="width: 100%; height: 360px;"></div>
            </section>
        </div>
        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="{% static 'assets/script.js' %}"></script>
    </body>
</html>